version: "3.9"
services:
  server:
    build:
      context: "./"
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: travels-db
      JWT_SECRET: zxcvbnmasdfghj111111
      GQL_PATH: "/graphql"
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    expose:
      - "6379"
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: travels-db
    volumes:
      - ./data:/data